
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./succes_assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)



def window_succes(window) :
    canvas = Canvas(
        window,
        bg = "#B9EBF6",
        height = 720,
        width = 1280,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)

    canvas.create_text(
        513.0,
        287.0,
        anchor="nw",
        text="login berhasil",
        fill="#000000",
        font=("Poppins Regular", 40 * -1)
    )

    canvas.create_text(
        1280/2,
        369.0,
        anchor="center",
        text="Terimakasih telah menggunakan layanan kami",
        fill="#000000",
        font=("Poppins Regular", 40 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
